<a href="https://colab.research.google.com/github/naphtron/ML/blob/main/numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a  = np.array([1,2,3])


print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3]
(3,)
int64
1
3
8


In [ ]:
b = a * np.array([2,0,2])
print(b)

[2 0 6]


In [ ]:
c = np.array([[1,2,3],[4,5,6],[8,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [8 8 9]]


##np array vs list

In [ ]:
l = [1,2,3]
# a = np.array([1,2,3])
l.append(4)
print(l)
# a.append(4) - won't work since np.array has no append method
print(a)


[1, 2, 3, 4]
[1 2 3]


In [ ]:
print(np.diag([1,2]))
print(np.linalg.inv(c))
print(np.linalg.det(c))

[[1 0]
 [0 2]]
[[ 1.         -2.          1.        ]
 [-4.          5.         -2.        ]
 [ 2.66666667 -2.66666667  1.        ]]
-2.9999999999999996


In [ ]:
bool_idx = c > 2
print(bool_idx)
print(c[bool_idx]) 

print(c[c>2])

b = np.where(c>2, c, -1)
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 8 8 9]
[3 4 5 6 8 8 9]
[[-1 -1  3]
 [ 4  5  6]
 [ 8  8  9]]


##Fancy Indexing

In [ ]:
a1 = np.array([10,19,30,41,50,61])
print(a1)
b1 = [1,3,5]
print(a1[b1])

[10 19 30 41 50 61]
[19 41 61]


##np.argwhere()

In [ ]:
even = np.argwhere(a1%2==0).flatten()
print("Even indices: ", even)
print(a1[even])

Even indices:  [0 2 4]
[10 30 50]


##np.arange()

In [ ]:
a2 = np.arange(1,7)
print(a2)
print(a2.shape)

# reshaping array
b2 = a2.reshape((2,3))
print(b2)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]


##np.newaxis()

In [ ]:
# b3 = a2[np.newaxis, :]
b3 = a2[:,np.newaxis]
print(b3.shape)
print(b3)

# np.newaxis() is very useful if your ML model requires data in a certain shape

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## np.concatenate

In [ ]:
a = np.array([[1,2],[3,4]])
print(a,"\n")

b = np.array([[5,6]])
c = np.concatenate((a,b.T), axis=1)
print("C:\n ",c , type(c))


[[1 2]
 [3 4]] 

C:
  [[1 2 5]
 [3 4 6]] <class 'numpy.ndarray'>


##np.hstack

In [ ]:
a = np.array([1,2,3,4])
b = np. array([5,6,7,8])

c = np.hstack((a,b))
print(c)
print(c.shape)

# np.hstack: Stack arrays in sequence horizontally (column wise).

[1 2 3 4 5 6 7 8]
(8,)


##np.vstack

In [ ]:
c = np.vstack((a,b))
print(c)
print(c.shape)
# np.vstack: Stack arrays in sequence vertically (row wise).

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


#Broadcasting

In [ ]:
x = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a = np.array([1,0,1])
y = x + a
print(y)


[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


##np.array.sum() and np.array.mean() 
##np.array.var() np.array.std()

In [ ]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

print(a)
print(a.sum(axis=None)) #sum all elements
print(a.sum(axis=0)) # sum row wise
print(a.sum(axis=1)) # sum column wise
print("\nMean\n")
print(a.mean(axis=None)) #mean all elements
print(a.mean(axis=0)) # mean row wise
print(a.mean(axis=1)) # mean column wise
print("\nstd\n")
print(a.std(axis=None)) #std all elements
print(a.std(axis=0)) #std row wise
print(a.std(axis=1)) # std column wise
print("\nvar\n")
print(a.var(axis=None)) #var all elements
print(a.var(axis=0)) # var row wise
print(a.var(axis=1)) # var column wise
print("\nmin\n")
print(a.min(axis=None)) #min all elements
print(a.min(axis=0)) # min row wise
print(a.min(axis=1)) # min column wise
print("\nmax\n")
print(a.max(axis=None)) #max all elements
print(a.max(axis=0)) # max row wise
print(a.max(axis=1)) # max column wise

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
[24 26 28 30 32 34 36]
[ 70 140]

Mean

15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]

std

5.385164807134504
[5. 5. 5. 5. 5. 5. 5.]
[2. 2.]

var

29.0
[25. 25. 25. 25. 25. 25. 25.]
[4. 4.]

min

7
[ 7  8  9 10 11 12 13]
[ 7 17]

max

23
[17 18 19 20 21 22 23]
[13 23]


##Datatypes

In [ ]:
x = np.array([1,2])
print(f"X: {x} Datatype:{x.dtype}")

#you can specify datatype
x1 = np.array([1.1,2.0], dtype=np.int32)
print(x1)
x2 = np.array([1.1,2.0], dtype=np.float64)
print(x2)

X: [1 2] Datatype:int64
[1 2]
[1.1 2. ]


##Copying Arrays

In [ ]:
#Don't
a = np.array([1,2,3])
b = a
b[0] = 42
print(b)
print(a)
# modifies both a and b since you copied the reference and this points to the same location in memory.

#Do
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0] = 42
print(b1)
print(a1)

[42  2  3]
[42  2  3]
[42  2  3]
[1 2 3]


##Generating Arrays

In [ ]:

a = np.zeros((2,3)) #Return a new array of given shape and type, filled with zeros.
print("np.zeros(2,3)\n",a,"\n")

b = np.ones((2,3)) #Return a new array of given shape and type, filled with ones.
print("np.ones(2,3)\n",b,"\n")

c = np.full((2,3), 5.0) #Return a new array of given shape and type, filled with passed value
print("np.full(2,3)\n",c,"\n")

d = np.eye(3) # Returns identity matrix
print("np.eye(3)\n",d,"\n")

e = np.arange(20) #Return evenly spaced values within a given interval
print("np.arange(20)\n",e,"\n")

f = np.linspace(0,10,5) # Return evenly spaced numbers over a specified interval
print("np.linspace(0,10,5)\n", f)

np.zeros(2,3)
 [[0. 0. 0.]
 [0. 0. 0.]] 

np.ones(2,3)
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.full(2,3)
 [[5. 5. 5.]
 [5. 5. 5.]] 

np.eye(3)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

np.arange(20)
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

np.linspace(0,10,5)
 [ 0.   2.5  5.   7.5 10. ]


##Random Numbers

In [ ]:
a = np.random.random((3,2)) #0-1
print(a)

b = np.random.randn(1000) #normal/ Gaussian
print(b.mean(), b.var())

c = np.random.randint(7,10,size=(3,3)) # or c = np.random.randint(low,high,size=[3,3])
print(c)

d = np.random.choice(5,size=10)

# or

e = np.random.choice([-7,-6,-8],size=10)

[[0.67425929 0.95782792]
 [0.31896959 0.14509079]
 [0.41578985 0.14853755]]
0.026674767900917086 1.1100969376681877
[[9 7 9]
 [7 8 9]
 [9 9 8]]


##Linear Algebra - Eigenvalues/Eigenvectors

In [ ]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues",eigenvalues,"\n")
print("Eigenvectors",eigenvectors) # column vectors

b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
#print(b==c)
print(np.allclose(b,c))

Eigenvalues [-0.37228132  5.37228132] 

Eigenvectors [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[ 0.30697009 -0.21062466]
True


##Solving Linear Systems

###Q: The admission fee at a small fair is 1.50 dollars for children and 4.00 dollars for adults. On a certain day, 2200 people enter the fair and $5050 is collectes. How mainy adults attended ?

In [ ]:
# x1 + x2 = 2200
#1.5x1 + 4.0x2 = 5050
#x1 is the number of children, x2 is the number of adults

In [ ]:
#Soln: Manual way
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

x = np.linalg.inv(A).dot(b)
print(x)

#Soln: np.linalg.solve()
# use this to solve linear equations
x1 = np.linalg.solve(A,b)
print(x1)

[1500.  700.]
[1500.  700.]


##Loading CSV files
##$np.loadtxt()$ and $np.genfromtxt()$

In [ ]:
data = np.loadtxt('spambase.csv', delimiter=",", dtype=np.float32)
data_is_also =  np.genfromtxt('spambase.csv', delimiter=",", dtype=np.float32)